/**
 * Common Unicode emojis with shortcode mappings, categories, and keywords
 * Based on common shortcodes used across platforms (Slack, Discord, GitHub)
 */

export interface UnicodeEmoji {
  shortcode: string;
  emoji: string;
  category: EmojiCategory;
  keywords?: string[];
}

export type EmojiCategory =
  | "smileys"
  | "gestures"
  | "hearts"
  | "animals"
  | "food"
  | "activities"
  | "nature"
  | "travel"
  | "crypto"
  | "misc";

export const EMOJI_CATEGORIES: Record<
  EmojiCategory,
  { label: string; icon: string }
> = {
  smileys: { label: "Smileys", icon: "😀" },
  gestures: { label: "Gestures", icon: "👍" },
  hearts: { label: "Hearts", icon: "❤️" },
  animals: { label: "Animals", icon: "🐶" },
  food: { label: "Food", icon: "🍕" },
  activities: { label: "Activities", icon: "⚽" },
  nature: { label: "Nature", icon: "🌲" },
  travel: { label: "Travel", icon: "🚗" },
  crypto: { label: "Crypto", icon: "₿" },
  misc: { label: "Misc", icon: "💡" },
};

export const UNICODE_EMOJIS: UnicodeEmoji[] = [
  // Smileys & Emotion
  {
    shortcode: "smile",
    emoji: "\u{1F604}",
    category: "smileys",
    keywords: ["happy", "joy", "grin", "pleased"],
  },
  {
    shortcode: "grinning",
    emoji: "\u{1F600}",
    category: "smileys",
    keywords: ["happy", "smile", "grin"],
  },
  {
    shortcode: "joy",
    emoji: "\u{1F602}",
    category: "smileys",
    keywords: ["tears", "laugh", "crying", "lol"],
  },
  {
    shortcode: "rofl",
    emoji: "\u{1F923}",
    category: "smileys",
    keywords: ["laugh", "floor", "rolling"],
  },
  {
    shortcode: "smiley",
    emoji: "\u{1F603}",
    category: "smileys",
    keywords: ["happy", "smile"],
  },
  {
    shortcode: "sweat_smile",
    emoji: "\u{1F605}",
    category: "smileys",
    keywords: ["happy", "nervous", "sweat"],
  },
  {
    shortcode: "laughing",
    emoji: "\u{1F606}",
    category: "smileys",
    keywords: ["happy", "laugh", "satisfied"],
  },
  {
    shortcode: "wink",
    emoji: "\u{1F609}",
    category: "smileys",
    keywords: ["flirt", "playful"],
  },
  {
    shortcode: "blush",
    emoji: "\u{1F60A}",
    category: "smileys",
    keywords: ["happy", "shy", "smile"],
  },
  {
    shortcode: "yum",
    emoji: "\u{1F60B}",
    category: "smileys",
    keywords: ["delicious", "tasty"],
  },
  {
    shortcode: "sunglasses",
    emoji: "\u{1F60E}",
    category: "smileys",
    keywords: ["cool", "swagger"],
  },
  {
    shortcode: "heart_eyes",
    emoji: "\u{1F60D}",
    category: "smileys",
    keywords: ["love", "adore", "crush"],
  },
  {
    shortcode: "kissing_heart",
    emoji: "\u{1F618}",
    category: "smileys",
    keywords: ["love", "kiss", "affection"],
  },
  {
    shortcode: "kissing",
    emoji: "\u{1F617}",
    category: "smileys",
    keywords: ["kiss", "love"],
  },
  {
    shortcode: "relaxed",
    emoji: "\u{263A}\u{FE0F}",
    category: "smileys",
    keywords: ["calm", "peaceful"],
  },
  {
    shortcode: "stuck_out_tongue",
    emoji: "\u{1F61B}",
    category: "smileys",
    keywords: ["playful", "silly"],
  },
  {
    shortcode: "stuck_out_tongue_winking_eye",
    emoji: "\u{1F61C}",
    category: "smileys",
    keywords: ["playful", "silly", "wink"],
  },
  {
    shortcode: "stuck_out_tongue_closed_eyes",
    emoji: "\u{1F61D}",
    category: "smileys",
    keywords: ["playful", "silly", "delicious"],
  },
  {
    shortcode: "money_mouth_face",
    emoji: "\u{1F911}",
    category: "smileys",
    keywords: ["rich", "money", "wealth"],
  },
  {
    shortcode: "hugs",
    emoji: "\u{1F917}",
    category: "smileys",
    keywords: ["hug", "embrace", "warm"],
  },
  {
    shortcode: "nerd_face",
    emoji: "\u{1F913}",
    category: "smileys",
    keywords: ["geek", "smart", "glasses"],
  },
  {
    shortcode: "smirk",
    emoji: "\u{1F60F}",
    category: "smileys",
    keywords: ["smug", "sly"],
  },
  {
    shortcode: "unamused",
    emoji: "\u{1F612}",
    category: "smileys",
    keywords: ["annoyed", "serious"],
  },
  {
    shortcode: "disappointed",
    emoji: "\u{1F61E}",
    category: "smileys",
    keywords: ["sad", "upset"],
  },
  {
    shortcode: "pensive",
    emoji: "\u{1F614}",
    category: "smileys",
    keywords: ["sad", "thoughtful"],
  },
  {
    shortcode: "worried",
    emoji: "\u{1F61F}",
    category: "smileys",
    keywords: ["anxious", "concerned"],
  },
  {
    shortcode: "confused",
    emoji: "\u{1F615}",
    category: "smileys",
    keywords: ["puzzled", "unsure"],
  },
  {
    shortcode: "slightly_frowning_face",
    emoji: "\u{1F641}",
    category: "smileys",
    keywords: ["sad", "frown"],
  },
  {
    shortcode: "frowning_face",
    emoji: "\u{2639}\u{FE0F}",
    category: "smileys",
    keywords: ["sad", "unhappy"],
  },
  {
    shortcode: "persevere",
    emoji: "\u{1F623}",
    category: "smileys",
    keywords: ["struggle", "frustrated"],
  },
  {
    shortcode: "confounded",
    emoji: "\u{1F616}",
    category: "smileys",
    keywords: ["confused", "frustrated"],
  },
  {
    shortcode: "tired_face",
    emoji: "\u{1F62B}",
    category: "smileys",
    keywords: ["exhausted", "weary"],
  },
  {
    shortcode: "weary",
    emoji: "\u{1F629}",
    category: "smileys",
    keywords: ["tired", "exhausted"],
  },
  {
    shortcode: "cry",
    emoji: "\u{1F622}",
    category: "smileys",
    keywords: ["sad", "tears", "upset"],
  },
  {
    shortcode: "sob",
    emoji: "\u{1F62D}",
    category: "smileys",
    keywords: ["cry", "tears", "sad"],
  },
  {
    shortcode: "triumph",
    emoji: "\u{1F624}",
    category: "smileys",
    keywords: ["angry", "frustrated", "steam"],
  },
  {
    shortcode: "angry",
    emoji: "\u{1F620}",
    category: "smileys",
    keywords: ["mad", "upset", "rage"],
  },
  {
    shortcode: "rage",
    emoji: "\u{1F621}",
    category: "smileys",
    keywords: ["angry", "furious", "mad"],
  },
  {
    shortcode: "no_mouth",
    emoji: "\u{1F636}",
    category: "smileys",
    keywords: ["silent", "speechless"],
  },
  {
    shortcode: "neutral_face",
    emoji: "\u{1F610}",
    category: "smileys",
    keywords: ["indifferent", "meh"],
  },
  {
    shortcode: "expressionless",
    emoji: "\u{1F611}",
    category: "smileys",
    keywords: ["blank", "deadpan"],
  },
  {
    shortcode: "hushed",
    emoji: "\u{1F62F}",
    category: "smileys",
    keywords: ["surprised", "quiet"],
  },
  {
    shortcode: "flushed",
    emoji: "\u{1F633}",
    category: "smileys",
    keywords: ["embarrassed", "shy"],
  },
  {
    shortcode: "astonished",
    emoji: "\u{1F632}",
    category: "smileys",
    keywords: ["shocked", "surprised"],
  },
  {
    shortcode: "open_mouth",
    emoji: "\u{1F62E}",
    category: "smileys",
    keywords: ["surprised", "wow"],
  },
  {
    shortcode: "scream",
    emoji: "\u{1F631}",
    category: "smileys",
    keywords: ["shocked", "scared", "omg"],
  },
  {
    shortcode: "fearful",
    emoji: "\u{1F628}",
    category: "smileys",
    keywords: ["scared", "afraid"],
  },
  {
    shortcode: "cold_sweat",
    emoji: "\u{1F630}",
    category: "smileys",
    keywords: ["nervous", "anxious"],
  },
  {
    shortcode: "disappointed_relieved",
    emoji: "\u{1F625}",
    category: "smileys",
    keywords: ["sad", "relieved", "phew"],
  },
  {
    shortcode: "sweat",
    emoji: "\u{1F613}",
    category: "smileys",
    keywords: ["nervous", "anxious"],
  },
  {
    shortcode: "sleeping",
    emoji: "\u{1F634}",
    category: "smileys",
    keywords: ["sleep", "tired", "zzz"],
  },
  {
    shortcode: "sleepy",
    emoji: "\u{1F62A}",
    category: "smileys",
    keywords: ["tired", "drowsy"],
  },
  {
    shortcode: "dizzy_face",
    emoji: "\u{1F635}",
    category: "smileys",
    keywords: ["confused", "disoriented"],
  },
  {
    shortcode: "zipper_mouth_face",
    emoji: "\u{1F910}",
    category: "smileys",
    keywords: ["secret", "silent", "sealed"],
  },
  {
    shortcode: "mask",
    emoji: "\u{1F637}",
    category: "smileys",
    keywords: ["sick", "health", "medical"],
  },
  {
    shortcode: "thermometer_face",
    emoji: "\u{1F912}",
    category: "smileys",
    keywords: ["sick", "fever", "ill"],
  },
  {
    shortcode: "head_bandage",
    emoji: "\u{1F915}",
    category: "smileys",
    keywords: ["injured", "hurt"],
  },
  {
    shortcode: "thinking",
    emoji: "\u{1F914}",
    category: "smileys",
    keywords: ["hmm", "pondering", "considering"],
  },
  {
    shortcode: "rolling_eyes",
    emoji: "\u{1F644}",
    category: "smileys",
    keywords: ["annoyed", "whatever"],
  },
  {
    shortcode: "upside_down_face",
    emoji: "\u{1F643}",
    category: "smileys",
    keywords: ["silly", "sarcastic"],
  },
  {
    shortcode: "face_with_hand_over_mouth",
    emoji: "\u{1F92D}",
    category: "smileys",
    keywords: ["oops", "giggle"],
  },
  {
    shortcode: "shushing_face",
    emoji: "\u{1F92B}",
    category: "smileys",
    keywords: ["quiet", "shh", "secret"],
  },
  {
    shortcode: "exploding_head",
    emoji: "\u{1F92F}",
    category: "smileys",
    keywords: ["mind", "blown", "shocked"],
  },
  {
    shortcode: "cowboy_hat_face",
    emoji: "\u{1F920}",
    category: "smileys",
    keywords: ["cowboy", "western"],
  },
  {
    shortcode: "partying_face",
    emoji: "\u{1F973}",
    category: "smileys",
    keywords: ["party", "celebrate", "fun"],
  },
  {
    shortcode: "woozy_face",
    emoji: "\u{1F974}",
    category: "smileys",
    keywords: ["dizzy", "drunk"],
  },
  {
    shortcode: "pleading_face",
    emoji: "\u{1F97A}",
    category: "smileys",
    keywords: ["please", "beg", "puppy eyes"],
  },
  {
    shortcode: "skull",
    emoji: "\u{1F480}",
    category: "smileys",
    keywords: ["dead", "dying", "lol"],
  },

  // Gestures & Body
  {
    shortcode: "thumbsup",
    emoji: "\u{1F44D}",
    category: "gestures",
    keywords: ["yes", "ok", "agree", "good"],
  },
  {
    shortcode: "+1",
    emoji: "\u{1F44D}",
    category: "gestures",
    keywords: ["yes", "ok", "agree", "good"],
  },
  {
    shortcode: "thumbsdown",
    emoji: "\u{1F44E}",
    category: "gestures",
    keywords: ["no", "bad", "disagree"],
  },
  {
    shortcode: "-1",
    emoji: "\u{1F44E}",
    category: "gestures",
    keywords: ["no", "bad", "disagree"],
  },
  {
    shortcode: "ok_hand",
    emoji: "\u{1F44C}",
    category: "gestures",
    keywords: ["ok", "perfect", "good"],
  },
  {
    shortcode: "punch",
    emoji: "\u{1F44A}",
    category: "gestures",
    keywords: ["fist", "bump", "hit"],
  },
  {
    shortcode: "fist",
    emoji: "\u{270A}",
    category: "gestures",
    keywords: ["punch", "power"],
  },
  {
    shortcode: "wave",
    emoji: "\u{1F44B}",
    category: "gestures",
    keywords: ["hello", "hi", "bye", "goodbye"],
  },
  {
    shortcode: "hand",
    emoji: "\u{270B}",
    category: "gestures",
    keywords: ["stop", "high five"],
  },
  {
    shortcode: "open_hands",
    emoji: "\u{1F450}",
    category: "gestures",
    keywords: ["hug"],
  },
  { shortcode: "point_up", emoji: "\u{261D}\u{FE0F}", category: "gestures" },
  { shortcode: "point_down", emoji: "\u{1F447}", category: "gestures" },
  { shortcode: "point_left", emoji: "\u{1F448}", category: "gestures" },
  { shortcode: "point_right", emoji: "\u{1F449}", category: "gestures" },
  {
    shortcode: "clap",
    emoji: "\u{1F44F}",
    category: "gestures",
    keywords: ["applause", "bravo", "congrats"],
  },
  {
    shortcode: "pray",
    emoji: "\u{1F64F}",
    category: "gestures",
    keywords: ["thanks", "please", "hope"],
  },
  {
    shortcode: "muscle",
    emoji: "\u{1F4AA}",
    category: "gestures",
    keywords: ["strong", "power", "flex"],
  },
  {
    shortcode: "metal",
    emoji: "\u{1F918}",
    category: "gestures",
    keywords: ["rock", "horns"],
  },
  {
    shortcode: "crossed_fingers",
    emoji: "\u{1F91E}",
    category: "gestures",
    keywords: ["luck", "hope"],
  },
  {
    shortcode: "v",
    emoji: "\u{270C}\u{FE0F}",
    category: "gestures",
    keywords: ["peace", "victory"],
  },
  {
    shortcode: "love_you_gesture",
    emoji: "\u{1F91F}",
    category: "gestures",
    keywords: ["love", "ily"],
  },
  {
    shortcode: "call_me_hand",
    emoji: "\u{1F919}",
    category: "gestures",
    keywords: ["call"],
  },
  {
    shortcode: "raised_back_of_hand",
    emoji: "\u{1F91A}",
    category: "gestures",
  },
  {
    shortcode: "handshake",
    emoji: "\u{1F91D}",
    category: "gestures",
    keywords: ["agreement", "deal"],
  },
  {
    shortcode: "writing_hand",
    emoji: "\u{270D}\u{FE0F}",
    category: "gestures",
    keywords: ["write", "note"],
  },
  {
    shortcode: "eyes",
    emoji: "\u{1F440}",
    category: "gestures",
    keywords: ["looking", "watching"],
  },
  {
    shortcode: "eye",
    emoji: "\u{1F441}\u{FE0F}",
    category: "gestures",
    keywords: ["see"],
  },
  {
    shortcode: "brain",
    emoji: "\u{1F9E0}",
    category: "gestures",
    keywords: ["smart", "think"],
  },

  // Hearts & Symbols
  {
    shortcode: "heart",
    emoji: "\u{2764}\u{FE0F}",
    category: "hearts",
    keywords: ["love", "like"],
  },
  {
    shortcode: "red_heart",
    emoji: "\u{2764}\u{FE0F}",
    category: "hearts",
    keywords: ["love", "like"],
  },
  {
    shortcode: "orange_heart",
    emoji: "\u{1F9E1}",
    category: "hearts",
    keywords: ["love"],
  },
  {
    shortcode: "yellow_heart",
    emoji: "\u{1F49B}",
    category: "hearts",
    keywords: ["love"],
  },
  {
    shortcode: "green_heart",
    emoji: "\u{1F49A}",
    category: "hearts",
    keywords: ["love"],
  },
  {
    shortcode: "blue_heart",
    emoji: "\u{1F499}",
    category: "hearts",
    keywords: ["love"],
  },
  {
    shortcode: "purple_heart",
    emoji: "\u{1F49C}",
    category: "hearts",
    keywords: ["love"],
  },
  {
    shortcode: "black_heart",
    emoji: "\u{1F5A4}",
    category: "hearts",
    keywords: ["dark"],
  },
  {
    shortcode: "broken_heart",
    emoji: "\u{1F494}",
    category: "hearts",
    keywords: ["sad", "heartbreak"],
  },
  {
    shortcode: "two_hearts",
    emoji: "\u{1F495}",
    category: "hearts",
    keywords: ["love"],
  },
  {
    shortcode: "sparkling_heart",
    emoji: "\u{1F496}",
    category: "hearts",
    keywords: ["love", "sparkle"],
  },
  {
    shortcode: "heartpulse",
    emoji: "\u{1F497}",
    category: "hearts",
    keywords: ["love"],
  },
  {
    shortcode: "heartbeat",
    emoji: "\u{1F493}",
    category: "hearts",
    keywords: ["love"],
  },
  {
    shortcode: "fire",
    emoji: "\u{1F525}",
    category: "hearts",
    keywords: ["hot", "burn", "flame", "lit"],
  },
  {
    shortcode: "star",
    emoji: "\u{2B50}",
    category: "hearts",
    keywords: ["favorite", "shine"],
  },
  {
    shortcode: "star2",
    emoji: "\u{1F31F}",
    category: "hearts",
    keywords: ["sparkle"],
  },
  {
    shortcode: "sparkles",
    emoji: "\u{2728}",
    category: "hearts",
    keywords: ["shine", "magic"],
  },
  {
    shortcode: "zap",
    emoji: "\u{26A1}",
    category: "hearts",
    keywords: ["lightning", "fast", "energy"],
  },
  {
    shortcode: "boom",
    emoji: "\u{1F4A5}",
    category: "hearts",
    keywords: ["explosion", "bang"],
  },
  {
    shortcode: "100",
    emoji: "\u{1F4AF}",
    category: "hearts",
    keywords: ["perfect", "score"],
  },
  {
    shortcode: "checkmark",
    emoji: "\u{2714}\u{FE0F}",
    category: "hearts",
    keywords: ["yes", "done"],
  },
  {
    shortcode: "white_check_mark",
    emoji: "\u{2705}",
    category: "hearts",
    keywords: ["yes", "done"],
  },
  {
    shortcode: "x",
    emoji: "\u{274C}",
    category: "hearts",
    keywords: ["no", "wrong"],
  },
  {
    shortcode: "question",
    emoji: "\u{2753}",
    category: "hearts",
    keywords: ["why", "help"],
  },
  {
    shortcode: "exclamation",
    emoji: "\u{2757}",
    category: "hearts",
    keywords: ["important", "attention"],
  },
  {
    shortcode: "warning",
    emoji: "\u{26A0}\u{FE0F}",
    category: "hearts",
    keywords: ["caution", "alert"],
  },

  // Animals
  {
    shortcode: "dog",
    emoji: "\u{1F436}",
    category: "animals",
    keywords: ["pet", "puppy"],
  },
  {
    shortcode: "cat",
    emoji: "\u{1F431}",
    category: "animals",
    keywords: ["pet", "kitty"],
  },
  { shortcode: "mouse", emoji: "\u{1F42D}", category: "animals" },
  {
    shortcode: "rabbit",
    emoji: "\u{1F430}",
    category: "animals",
    keywords: ["bunny"],
  },
  { shortcode: "bear", emoji: "\u{1F43B}", category: "animals" },
  {
    shortcode: "panda_face",
    emoji: "\u{1F43C}",
    category: "animals",
    keywords: ["panda"],
  },
  { shortcode: "lion", emoji: "\u{1F981}", category: "animals" },
  { shortcode: "pig", emoji: "\u{1F437}", category: "animals" },
  { shortcode: "frog", emoji: "\u{1F438}", category: "animals" },
  {
    shortcode: "monkey_face",
    emoji: "\u{1F435}",
    category: "animals",
    keywords: ["monkey"],
  },
  {
    shortcode: "see_no_evil",
    emoji: "\u{1F648}",
    category: "animals",
    keywords: ["monkey"],
  },
  {
    shortcode: "hear_no_evil",
    emoji: "\u{1F649}",
    category: "animals",
    keywords: ["monkey"],
  },
  {
    shortcode: "speak_no_evil",
    emoji: "\u{1F64A}",
    category: "animals",
    keywords: ["monkey"],
  },
  { shortcode: "chicken", emoji: "\u{1F414}", category: "animals" },
  { shortcode: "penguin", emoji: "\u{1F427}", category: "animals" },
  { shortcode: "bird", emoji: "\u{1F426}", category: "animals" },
  { shortcode: "eagle", emoji: "\u{1F985}", category: "animals" },
  { shortcode: "duck", emoji: "\u{1F986}", category: "animals" },
  { shortcode: "owl", emoji: "\u{1F989}", category: "animals" },
  { shortcode: "bat", emoji: "\u{1F987}", category: "animals" },
  { shortcode: "wolf", emoji: "\u{1F43A}", category: "animals" },
  {
    shortcode: "fox_face",
    emoji: "\u{1F98A}",
    category: "animals",
    keywords: ["fox"],
  },
  {
    shortcode: "unicorn",
    emoji: "\u{1F984}",
    category: "animals",
    keywords: ["magic"],
  },
  { shortcode: "bee", emoji: "\u{1F41D}", category: "animals" },
  {
    shortcode: "bug",
    emoji: "\u{1F41B}",
    category: "animals",
    keywords: ["insect"],
  },
  { shortcode: "butterfly", emoji: "\u{1F98B}", category: "animals" },
  {
    shortcode: "snail",
    emoji: "\u{1F40C}",
    category: "animals",
    keywords: ["slow"],
  },
  { shortcode: "turtle", emoji: "\u{1F422}", category: "animals" },
  { shortcode: "snake", emoji: "\u{1F40D}", category: "animals" },
  { shortcode: "dragon", emoji: "\u{1F409}", category: "animals" },
  { shortcode: "octopus", emoji: "\u{1F419}", category: "animals" },
  { shortcode: "whale", emoji: "\u{1F433}", category: "animals" },
  { shortcode: "dolphin", emoji: "\u{1F42C}", category: "animals" },
  { shortcode: "shark", emoji: "\u{1F988}", category: "animals" },
  { shortcode: "crab", emoji: "\u{1F980}", category: "animals" },
  { shortcode: "shrimp", emoji: "\u{1F990}", category: "animals" },

  // Food & Drink
  {
    shortcode: "apple",
    emoji: "\u{1F34E}",
    category: "food",
    keywords: ["fruit", "healthy"],
  },
  {
    shortcode: "green_apple",
    emoji: "\u{1F34F}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "banana",
    emoji: "\u{1F34C}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "orange",
    emoji: "\u{1F34A}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "lemon",
    emoji: "\u{1F34B}",
    category: "food",
    keywords: ["fruit", "sour"],
  },
  {
    shortcode: "watermelon",
    emoji: "\u{1F349}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "grapes",
    emoji: "\u{1F347}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "strawberry",
    emoji: "\u{1F353}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "peach",
    emoji: "\u{1F351}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "cherries",
    emoji: "\u{1F352}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "pineapple",
    emoji: "\u{1F34D}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "avocado",
    emoji: "\u{1F951}",
    category: "food",
    keywords: ["fruit"],
  },
  {
    shortcode: "tomato",
    emoji: "\u{1F345}",
    category: "food",
    keywords: ["vegetable"],
  },
  {
    shortcode: "eggplant",
    emoji: "\u{1F346}",
    category: "food",
    keywords: ["vegetable"],
  },
  {
    shortcode: "carrot",
    emoji: "\u{1F955}",
    category: "food",
    keywords: ["vegetable"],
  },
  {
    shortcode: "corn",
    emoji: "\u{1F33D}",
    category: "food",
    keywords: ["vegetable"],
  },
  {
    shortcode: "pizza",
    emoji: "\u{1F355}",
    category: "food",
    keywords: ["food", "italian"],
  },
  {
    shortcode: "hamburger",
    emoji: "\u{1F354}",
    category: "food",
    keywords: ["burger", "fast food"],
  },
  {
    shortcode: "fries",
    emoji: "\u{1F35F}",
    category: "food",
    keywords: ["fast food"],
  },
  {
    shortcode: "hotdog",
    emoji: "\u{1F32D}",
    category: "food",
    keywords: ["fast food"],
  },
  {
    shortcode: "taco",
    emoji: "\u{1F32E}",
    category: "food",
    keywords: ["mexican"],
  },
  {
    shortcode: "burrito",
    emoji: "\u{1F32F}",
    category: "food",
    keywords: ["mexican"],
  },
  {
    shortcode: "popcorn",
    emoji: "\u{1F37F}",
    category: "food",
    keywords: ["snack"],
  },
  {
    shortcode: "sushi",
    emoji: "\u{1F363}",
    category: "food",
    keywords: ["japanese"],
  },
  {
    shortcode: "ramen",
    emoji: "\u{1F35C}",
    category: "food",
    keywords: ["noodles"],
  },
  {
    shortcode: "cookie",
    emoji: "\u{1F36A}",
    category: "food",
    keywords: ["dessert"],
  },
  {
    shortcode: "cake",
    emoji: "\u{1F370}",
    category: "food",
    keywords: ["dessert"],
  },
  {
    shortcode: "birthday",
    emoji: "\u{1F382}",
    category: "food",
    keywords: ["cake", "party"],
  },
  {
    shortcode: "ice_cream",
    emoji: "\u{1F368}",
    category: "food",
    keywords: ["dessert", "cold"],
  },
  {
    shortcode: "doughnut",
    emoji: "\u{1F369}",
    category: "food",
    keywords: ["dessert"],
  },
  {
    shortcode: "chocolate_bar",
    emoji: "\u{1F36B}",
    category: "food",
    keywords: ["candy", "dessert"],
  },
  {
    shortcode: "candy",
    emoji: "\u{1F36C}",
    category: "food",
    keywords: ["sweet"],
  },
  {
    shortcode: "coffee",
    emoji: "\u{2615}",
    category: "food",
    keywords: ["drink", "cafe"],
  },
  {
    shortcode: "tea",
    emoji: "\u{1F375}",
    category: "food",
    keywords: ["drink"],
  },
  {
    shortcode: "beer",
    emoji: "\u{1F37A}",
    category: "food",
    keywords: ["drink", "alcohol"],
  },
  {
    shortcode: "beers",
    emoji: "\u{1F37B}",
    category: "food",
    keywords: ["drink", "cheers"],
  },
  {
    shortcode: "wine_glass",
    emoji: "\u{1F377}",
    category: "food",
    keywords: ["wine", "drink"],
  },
  {
    shortcode: "cocktail",
    emoji: "\u{1F378}",
    category: "food",
    keywords: ["drink", "party"],
  },
  {
    shortcode: "champagne",
    emoji: "\u{1F37E}",
    category: "food",
    keywords: ["drink", "celebrate"],
  },

  // Activities & Objects
  {
    shortcode: "soccer",
    emoji: "\u{26BD}",
    category: "activities",
    keywords: ["football", "sport"],
  },
  {
    shortcode: "basketball",
    emoji: "\u{1F3C0}",
    category: "activities",
    keywords: ["sport"],
  },
  {
    shortcode: "football",
    emoji: "\u{1F3C8}",
    category: "activities",
    keywords: ["sport"],
  },
  {
    shortcode: "baseball",
    emoji: "\u{26BE}",
    category: "activities",
    keywords: ["sport"],
  },
  {
    shortcode: "tennis",
    emoji: "\u{1F3BE}",
    category: "activities",
    keywords: ["sport"],
  },
  {
    shortcode: "golf",
    emoji: "\u{26F3}",
    category: "activities",
    keywords: ["sport"],
  },
  {
    shortcode: "trophy",
    emoji: "\u{1F3C6}",
    category: "activities",
    keywords: ["winner", "award"],
  },
  {
    shortcode: "medal_sports",
    emoji: "\u{1F3C5}",
    category: "activities",
    keywords: ["winner"],
  },
  {
    shortcode: "guitar",
    emoji: "\u{1F3B8}",
    category: "activities",
    keywords: ["music"],
  },
  {
    shortcode: "microphone",
    emoji: "\u{1F3A4}",
    category: "activities",
    keywords: ["music"],
  },
  {
    shortcode: "headphones",
    emoji: "\u{1F3A7}",
    category: "activities",
    keywords: ["music"],
  },
  {
    shortcode: "video_game",
    emoji: "\u{1F3AE}",
    category: "activities",
    keywords: ["gaming"],
  },
  {
    shortcode: "dart",
    emoji: "\u{1F3AF}",
    category: "activities",
    keywords: ["game"],
  },
  {
    shortcode: "game_die",
    emoji: "\u{1F3B2}",
    category: "activities",
    keywords: ["dice"],
  },
  {
    shortcode: "art",
    emoji: "\u{1F3A8}",
    category: "activities",
    keywords: ["paint"],
  },
  {
    shortcode: "movie_camera",
    emoji: "\u{1F3A5}",
    category: "activities",
    keywords: ["film"],
  },
  {
    shortcode: "camera",
    emoji: "\u{1F4F7}",
    category: "activities",
    keywords: ["photo"],
  },
  {
    shortcode: "tv",
    emoji: "\u{1F4FA}",
    category: "activities",
    keywords: ["television"],
  },
  {
    shortcode: "computer",
    emoji: "\u{1F4BB}",
    category: "activities",
    keywords: ["laptop", "tech"],
  },
  {
    shortcode: "keyboard",
    emoji: "\u{2328}\u{FE0F}",
    category: "activities",
    keywords: ["type"],
  },
  {
    shortcode: "iphone",
    emoji: "\u{1F4F1}",
    category: "activities",
    keywords: ["phone"],
  },
  {
    shortcode: "telephone",
    emoji: "\u{260E}\u{FE0F}",
    category: "activities",
    keywords: ["phone"],
  },
  {
    shortcode: "bulb",
    emoji: "\u{1F4A1}",
    category: "activities",
    keywords: ["idea", "light"],
  },
  { shortcode: "flashlight", emoji: "\u{1F526}", category: "activities" },
  {
    shortcode: "wrench",
    emoji: "\u{1F527}",
    category: "activities",
    keywords: ["tool", "fix"],
  },
  {
    shortcode: "hammer",
    emoji: "\u{1F528}",
    category: "activities",
    keywords: ["tool", "build"],
  },
  {
    shortcode: "gear",
    emoji: "\u{2699}\u{FE0F}",
    category: "activities",
    keywords: ["settings"],
  },
  {
    shortcode: "link",
    emoji: "\u{1F517}",
    category: "activities",
    keywords: ["chain", "url"],
  },
  {
    shortcode: "lock",
    emoji: "\u{1F512}",
    category: "activities",
    keywords: ["secure", "private"],
  },
  {
    shortcode: "unlock",
    emoji: "\u{1F513}",
    category: "activities",
    keywords: ["open"],
  },
  {
    shortcode: "key",
    emoji: "\u{1F511}",
    category: "activities",
    keywords: ["password"],
  },
  {
    shortcode: "mag",
    emoji: "\u{1F50D}",
    category: "activities",
    keywords: ["search", "find"],
  },
  {
    shortcode: "hourglass",
    emoji: "\u{231B}",
    category: "activities",
    keywords: ["time"],
  },
  {
    shortcode: "alarm_clock",
    emoji: "\u{23F0}",
    category: "activities",
    keywords: ["time"],
  },
  {
    shortcode: "stopwatch",
    emoji: "\u{23F1}\u{FE0F}",
    category: "activities",
    keywords: ["time"],
  },
  {
    shortcode: "calendar",
    emoji: "\u{1F4C5}",
    category: "activities",
    keywords: ["date"],
  },
  {
    shortcode: "memo",
    emoji: "\u{1F4DD}",
    category: "activities",
    keywords: ["note", "write"],
  },
  {
    shortcode: "pencil2",
    emoji: "\u{270F}\u{FE0F}",
    category: "activities",
    keywords: ["write"],
  },
  {
    shortcode: "scissors",
    emoji: "\u{2702}\u{FE0F}",
    category: "activities",
    keywords: ["cut"],
  },
  {
    shortcode: "paperclip",
    emoji: "\u{1F4CE}",
    category: "activities",
    keywords: ["attach"],
  },
  {
    shortcode: "bookmark",
    emoji: "\u{1F516}",
    category: "activities",
    keywords: ["save"],
  },
  {
    shortcode: "books",
    emoji: "\u{1F4DA}",
    category: "activities",
    keywords: ["library"],
  },
  {
    shortcode: "book",
    emoji: "\u{1F4D6}",
    category: "activities",
    keywords: ["read"],
  },
  {
    shortcode: "notebook",
    emoji: "\u{1F4D3}",
    category: "activities",
    keywords: ["write"],
  },
  {
    shortcode: "newspaper",
    emoji: "\u{1F4F0}",
    category: "activities",
    keywords: ["news"],
  },
  {
    shortcode: "envelope",
    emoji: "\u{2709}\u{FE0F}",
    category: "activities",
    keywords: ["mail"],
  },
  {
    shortcode: "email",
    emoji: "\u{1F4E7}",
    category: "activities",
    keywords: ["mail"],
  },
  {
    shortcode: "mailbox",
    emoji: "\u{1F4EB}",
    category: "activities",
    keywords: ["mail"],
  },
  {
    shortcode: "package",
    emoji: "\u{1F4E6}",
    category: "activities",
    keywords: ["box"],
  },
  {
    shortcode: "gift",
    emoji: "\u{1F381}",
    category: "activities",
    keywords: ["present"],
  },
  {
    shortcode: "balloon",
    emoji: "\u{1F388}",
    category: "activities",
    keywords: ["party"],
  },
  {
    shortcode: "tada",
    emoji: "\u{1F389}",
    category: "activities",
    keywords: ["party", "celebrate"],
  },
  {
    shortcode: "confetti_ball",
    emoji: "\u{1F38A}",
    category: "activities",
    keywords: ["party"],
  },
  {
    shortcode: "ribbon",
    emoji: "\u{1F380}",
    category: "activities",
    keywords: ["gift"],
  },
  {
    shortcode: "medal_military",
    emoji: "\u{1F396}\u{FE0F}",
    category: "activities",
    keywords: ["award"],
  },

  // Nature & Weather
  {
    shortcode: "sunny",
    emoji: "\u{2600}\u{FE0F}",
    category: "nature",
    keywords: ["sun", "weather"],
  },
  {
    shortcode: "cloud",
    emoji: "\u{2601}\u{FE0F}",
    category: "nature",
    keywords: ["weather"],
  },
  {
    shortcode: "rain_cloud",
    emoji: "\u{1F327}\u{FE0F}",
    category: "nature",
    keywords: ["rain"],
  },
  {
    shortcode: "thunder_cloud_and_rain",
    emoji: "\u{26C8}\u{FE0F}",
    category: "nature",
    keywords: ["storm"],
  },
  {
    shortcode: "rainbow",
    emoji: "\u{1F308}",
    category: "nature",
    keywords: ["color"],
  },
  {
    shortcode: "snowflake",
    emoji: "\u{2744}\u{FE0F}",
    category: "nature",
    keywords: ["snow", "cold"],
  },
  {
    shortcode: "snowman",
    emoji: "\u{26C4}",
    category: "nature",
    keywords: ["snow"],
  },
  {
    shortcode: "wind_face",
    emoji: "\u{1F32C}\u{FE0F}",
    category: "nature",
    keywords: ["wind"],
  },
  {
    shortcode: "tornado",
    emoji: "\u{1F32A}\u{FE0F}",
    category: "nature",
    keywords: ["storm"],
  },
  {
    shortcode: "ocean",
    emoji: "\u{1F30A}",
    category: "nature",
    keywords: ["sea", "water"],
  },
  {
    shortcode: "droplet",
    emoji: "\u{1F4A7}",
    category: "nature",
    keywords: ["water"],
  },
  {
    shortcode: "sun_with_face",
    emoji: "\u{1F31E}",
    category: "nature",
    keywords: ["sun"],
  },
  {
    shortcode: "full_moon",
    emoji: "\u{1F315}",
    category: "nature",
    keywords: ["moon"],
  },
  {
    shortcode: "new_moon",
    emoji: "\u{1F311}",
    category: "nature",
    keywords: ["moon"],
  },
  {
    shortcode: "crescent_moon",
    emoji: "\u{1F319}",
    category: "nature",
    keywords: ["moon"],
  },
  {
    shortcode: "earth_americas",
    emoji: "\u{1F30E}",
    category: "nature",
    keywords: ["earth"],
  },
  {
    shortcode: "earth_africa",
    emoji: "\u{1F30D}",
    category: "nature",
    keywords: ["earth"],
  },
  {
    shortcode: "earth_asia",
    emoji: "\u{1F30F}",
    category: "nature",
    keywords: ["earth"],
  },
  {
    shortcode: "globe_with_meridians",
    emoji: "\u{1F310}",
    category: "nature",
    keywords: ["globe"],
  },
  {
    shortcode: "sun_behind_cloud",
    emoji: "\u{26C5}",
    category: "nature",
    keywords: ["weather"],
  },
  {
    shortcode: "rose",
    emoji: "\u{1F339}",
    category: "nature",
    keywords: ["flower"],
  },
  {
    shortcode: "sunflower",
    emoji: "\u{1F33B}",
    category: "nature",
    keywords: ["flower"],
  },
  {
    shortcode: "tulip",
    emoji: "\u{1F337}",
    category: "nature",
    keywords: ["flower"],
  },
  {
    shortcode: "cherry_blossom",
    emoji: "\u{1F338}",
    category: "nature",
    keywords: ["flower"],
  },
  {
    shortcode: "hibiscus",
    emoji: "\u{1F33A}",
    category: "nature",
    keywords: ["flower"],
  },
  {
    shortcode: "bouquet",
    emoji: "\u{1F490}",
    category: "nature",
    keywords: ["flowers"],
  },
  {
    shortcode: "seedling",
    emoji: "\u{1F331}",
    category: "nature",
    keywords: ["plant"],
  },
  {
    shortcode: "evergreen_tree",
    emoji: "\u{1F332}",
    category: "nature",
    keywords: ["tree"],
  },
  {
    shortcode: "deciduous_tree",
    emoji: "\u{1F333}",
    category: "nature",
    keywords: ["tree"],
  },
  {
    shortcode: "palm_tree",
    emoji: "\u{1F334}",
    category: "nature",
    keywords: ["tree"],
  },
  {
    shortcode: "cactus",
    emoji: "\u{1F335}",
    category: "nature",
    keywords: ["plant"],
  },
  {
    shortcode: "herb",
    emoji: "\u{1F33F}",
    category: "nature",
    keywords: ["plant"],
  },
  {
    shortcode: "four_leaf_clover",
    emoji: "\u{1F340}",
    category: "nature",
    keywords: ["luck"],
  },
  {
    shortcode: "maple_leaf",
    emoji: "\u{1F341}",
    category: "nature",
    keywords: ["leaf"],
  },
  {
    shortcode: "fallen_leaf",
    emoji: "\u{1F342}",
    category: "nature",
    keywords: ["autumn"],
  },
  {
    shortcode: "mushroom",
    emoji: "\u{1F344}",
    category: "nature",
    keywords: ["fungus"],
  },

  // Travel & Places
  {
    shortcode: "car",
    emoji: "\u{1F697}",
    category: "travel",
    keywords: ["vehicle", "drive"],
  },
  {
    shortcode: "taxi",
    emoji: "\u{1F695}",
    category: "travel",
    keywords: ["car"],
  },
  {
    shortcode: "bus",
    emoji: "\u{1F68C}",
    category: "travel",
    keywords: ["vehicle"],
  },
  {
    shortcode: "truck",
    emoji: "\u{1F69A}",
    category: "travel",
    keywords: ["vehicle"],
  },
  {
    shortcode: "bike",
    emoji: "\u{1F6B2}",
    category: "travel",
    keywords: ["bicycle"],
  },
  { shortcode: "motorcycle", emoji: "\u{1F3CD}\u{FE0F}", category: "travel" },
  {
    shortcode: "airplane",
    emoji: "\u{2708}\u{FE0F}",
    category: "travel",
    keywords: ["plane"],
  },
  {
    shortcode: "rocket",
    emoji: "\u{1F680}",
    category: "travel",
    keywords: ["space"],
  },
  { shortcode: "helicopter", emoji: "\u{1F681}", category: "travel" },
  {
    shortcode: "boat",
    emoji: "\u{26F5}",
    category: "travel",
    keywords: ["ship"],
  },
  {
    shortcode: "ship",
    emoji: "\u{1F6A2}",
    category: "travel",
    keywords: ["boat"],
  },
  {
    shortcode: "anchor",
    emoji: "\u{2693}",
    category: "travel",
    keywords: ["ship"],
  },
  { shortcode: "train", emoji: "\u{1F686}", category: "travel" },
  {
    shortcode: "metro",
    emoji: "\u{1F687}",
    category: "travel",
    keywords: ["subway"],
  },
  {
    shortcode: "house",
    emoji: "\u{1F3E0}",
    category: "travel",
    keywords: ["home"],
  },
  {
    shortcode: "office",
    emoji: "\u{1F3E2}",
    category: "travel",
    keywords: ["building"],
  },
  {
    shortcode: "hospital",
    emoji: "\u{1F3E5}",
    category: "travel",
    keywords: ["medical"],
  },
  {
    shortcode: "school",
    emoji: "\u{1F3EB}",
    category: "travel",
    keywords: ["education"],
  },
  {
    shortcode: "church",
    emoji: "\u{26EA}",
    category: "travel",
    keywords: ["religion"],
  },
  {
    shortcode: "tent",
    emoji: "\u{26FA}",
    category: "travel",
    keywords: ["camping"],
  },
  { shortcode: "mountain", emoji: "\u{26F0}\u{FE0F}", category: "travel" },
  {
    shortcode: "camping",
    emoji: "\u{1F3D5}\u{FE0F}",
    category: "travel",
    keywords: ["tent"],
  },
  {
    shortcode: "beach_umbrella",
    emoji: "\u{1F3D6}\u{FE0F}",
    category: "travel",
    keywords: ["beach"],
  },
  { shortcode: "desert", emoji: "\u{1F3DC}\u{FE0F}", category: "travel" },
  {
    shortcode: "desert_island",
    emoji: "\u{1F3DD}\u{FE0F}",
    category: "travel",
  },
  {
    shortcode: "national_park",
    emoji: "\u{1F3DE}\u{FE0F}",
    category: "travel",
    keywords: ["park"],
  },
  {
    shortcode: "stadium",
    emoji: "\u{1F3DF}\u{FE0F}",
    category: "travel",
    keywords: ["sports"],
  },
  {
    shortcode: "statue_of_liberty",
    emoji: "\u{1F5FD}",
    category: "travel",
    keywords: ["nyc"],
  },
  { shortcode: "japan", emoji: "\u{1F5FE}", category: "travel" },
  {
    shortcode: "moyai",
    emoji: "\u{1F5FF}",
    category: "travel",
    keywords: ["moai", "stone"],
  },

  // Bitcoin/Crypto related
  {
    shortcode: "bitcoin",
    emoji: "\u{20BF}",
    category: "crypto",
    keywords: ["btc", "crypto", "money"],
  },
  {
    shortcode: "moneybag",
    emoji: "\u{1F4B0}",
    category: "crypto",
    keywords: ["money", "rich"],
  },
  {
    shortcode: "money_with_wings",
    emoji: "\u{1F4B8}",
    category: "crypto",
    keywords: ["money"],
  },
  {
    shortcode: "dollar",
    emoji: "\u{1F4B5}",
    category: "crypto",
    keywords: ["money"],
  },
  {
    shortcode: "euro",
    emoji: "\u{1F4B6}",
    category: "crypto",
    keywords: ["money"],
  },
  {
    shortcode: "yen",
    emoji: "\u{1F4B4}",
    category: "crypto",
    keywords: ["money"],
  },
  {
    shortcode: "pound",
    emoji: "\u{1F4B7}",
    category: "crypto",
    keywords: ["money"],
  },
  {
    shortcode: "gem",
    emoji: "\u{1F48E}",
    category: "crypto",
    keywords: ["diamond", "valuable"],
  },
  {
    shortcode: "chart",
    emoji: "\u{1F4C8}",
    category: "crypto",
    keywords: ["up", "growth", "stonks"],
  },
  {
    shortcode: "chart_with_upwards_trend",
    emoji: "\u{1F4C8}",
    category: "crypto",
    keywords: ["up", "growth"],
  },
  {
    shortcode: "chart_with_downwards_trend",
    emoji: "\u{1F4C9}",
    category: "crypto",
    keywords: ["down", "loss"],
  },

  // Misc popular
  {
    shortcode: "zzz",
    emoji: "\u{1F4A4}",
    category: "misc",
    keywords: ["sleep", "tired"],
  },
  {
    shortcode: "poop",
    emoji: "\u{1F4A9}",
    category: "misc",
    keywords: ["shit", "crap"],
  },
  {
    shortcode: "hankey",
    emoji: "\u{1F4A9}",
    category: "misc",
    keywords: ["poop", "shit"],
  },
  {
    shortcode: "ghost",
    emoji: "\u{1F47B}",
    category: "misc",
    keywords: ["spooky", "halloween"],
  },
  {
    shortcode: "alien",
    emoji: "\u{1F47D}",
    category: "misc",
    keywords: ["ufo", "space"],
  },
  {
    shortcode: "robot",
    emoji: "\u{1F916}",
    category: "misc",
    keywords: ["bot", "ai"],
  },
  {
    shortcode: "jack_o_lantern",
    emoji: "\u{1F383}",
    category: "misc",
    keywords: ["halloween"],
  },
  {
    shortcode: "santa",
    emoji: "\u{1F385}",
    category: "misc",
    keywords: ["christmas"],
  },
  {
    shortcode: "christmas_tree",
    emoji: "\u{1F384}",
    category: "misc",
    keywords: ["christmas"],
  },
  { shortcode: "egg", emoji: "\u{1F95A}", category: "misc" },
  {
    shortcode: "crown",
    emoji: "\u{1F451}",
    category: "misc",
    keywords: ["king", "queen"],
  },
  {
    shortcode: "ring",
    emoji: "\u{1F48D}",
    category: "misc",
    keywords: ["wedding"],
  },
  {
    shortcode: "lipstick",
    emoji: "\u{1F484}",
    category: "misc",
    keywords: ["makeup"],
  },
  {
    shortcode: "pill",
    emoji: "\u{1F48A}",
    category: "misc",
    keywords: ["medicine"],
  },
  {
    shortcode: "syringe",
    emoji: "\u{1F489}",
    category: "misc",
    keywords: ["needle", "vaccine"],
  },
  {
    shortcode: "cigarette",
    emoji: "\u{1F6AC}",
    category: "misc",
    keywords: ["smoke"],
  },
  {
    shortcode: "coffin",
    emoji: "\u{26B0}\u{FE0F}",
    category: "misc",
    keywords: ["death"],
  },
];
