import { describe, expect, it, beforeEach } from "vitest";

import { hkdf } from "@noble/hashes/hkdf.js";
import { sha256 } from "@noble/hashes/sha2.js";
import { schnorr } from "@noble/curves/secp256k1.js";

import {
  _resetGroupKeyMemoForTests,
  banlistLocator,
  baseRekeyGroupKey,
  bytesToHex,
  channelGroupKey,
  channelRekeyGroupKey,
  communityIdOf,
  controlGroupKey,
  controlSignerGroupKey,
  dissolvedGroupKey,
  epochKeyCommitment,
  exportGroupKeyMemo,
  grantLocator,
  guestbookGroupKey,
  hex32,
  importGroupKeyMemo,
  inviteBundleKey,
  inviteLinksLocator,
  onGroupKeyMemoDirty,
  pinsLocator,
  recipientLocator,
  verifyCommunityId,
} from "./derive";

const A = new Uint8Array(32).fill(1);
const B = new Uint8Array(32).fill(2);
const C = new Uint8Array(32).fill(3);
const R = new Uint8Array(32).fill(0xab);

beforeEach(() => {
  _resetGroupKeyMemoForTests();
});

/**
 * Fixed vectors, generated by running this port and armada `bc19d1f`'s
 * `src/concord/lib/derive.ts` side by side over the same inputs and asserting
 * every output matched. They are the point of this file.
 *
 * Everything else here is structural — deterministic, distinct, epoch-rolling —
 * and would pass on ANY self-consistent implementation, including a wrong one.
 * Only pinned bytes catch the failure that actually matters: a derivation that
 * is internally consistent but disagrees with every other Concord client, which
 * presents as "the community is empty" rather than as an error.
 */
const VECTORS = {
  "channel.pk":
    "20b59d9cc1472395cf5c954dbd2e6322c0ca005b08004f8f443a2f65d3c8b8aa",
  "channel.pk@7":
    "27526e33567b8b5359cf3be7214d3b87dcaf438a6f814c0fea55f632ceeffca7",
  "channel.convKey":
    "b3981d32dc407f390642ca3e51d145c82e092b889e0fd7164b0ebb4579cf296e",
  "channel.sk":
    "4b902405c5fd7f0b2e5046cd61fb8ceb13a1874b8e9fddaf280e5ed2e3359fa5",
  "control.pk":
    "57d6c4ac20f59c5b016fc1d4d81df87cd85449564640b5d5dbb8d0e89f6fcb0a",
  "control.convKey":
    "87a02b010e0166c458bfe0fae8070047d962ceab6d8e43fac6d852ac568935ff",
  "controlSigner.pk":
    "2b33cd3260934461d8dbb611fc2d7d081bb62a18cdd70c58f44104d1e581f98f",
  "guestbook.pk":
    "127e08c5f7121ad2989ef2e259b5ed1b39c807a50097b0d9f17099216668fbab",
  "dissolved.pk":
    "4ec4eed668302ea2c40ae632d9c87819169de28865910c462df2ca85b3ec0010",
  "channelRekey.pk":
    "50e50179593692b590c19d5f256b0c2edea163883b48f1a930258ee8afee4d7c",
  "baseRekey.pk":
    "32a09463ee1304cde07d48ab19028684d742b6b7170481a700a240d9c70caf4a",
  grantLocator:
    "713ebaaab5e5abe7a6f5b359aa18aef61465dc8f2acf0537020332fc299fef5d",
  pinsLocator:
    "6e1aa2cb6c78baed7d417d2f6432b1b651b8b605db58515d0749f400b0593a00",
  banlistLocator:
    "cf2767777adcceb8a2ce51d5c3d3c20de9c74bf4867bc2373e5b12eacb5c73d8",
  inviteLinksLocator:
    "481a34be5ddde159cb6c3eea86292469ee2663d2e2e3fc3d2b666b98f7189f2c",
  recipientLocator:
    "dfe3f8953b7c59755bbbb3f6edc777220cd7f0545c83fa01334b242f4db04a33",
  inviteBundleKey:
    "94bf8b0d89e579ddaeccf8d9db3f5de5c86a1259c597f2560ff0120173bc5e1f",
  communityIdOf:
    "637fba842161c1360163b53a5c6ad5c77ddba0759949a5f6285fc5e9b6d114c0",
  epochKeyCommitment:
    "cbf65d7d59ee87ce0dca143892b56711d4cda9c147f4109b63defcf450c8beb7",
} as const;

describe("frozen vectors (CORD-02 Appendix A)", () => {
  it("matches armada bc19d1f byte for byte", () => {
    expect(channelGroupKey(A, B, 0).pk).toBe(VECTORS["channel.pk"]);
    expect(channelGroupKey(A, B, 7).pk).toBe(VECTORS["channel.pk@7"]);
    expect(bytesToHex(channelGroupKey(A, B, 0).convKey)).toBe(
      VECTORS["channel.convKey"],
    );
    expect(bytesToHex(channelGroupKey(A, B, 0).sk)).toBe(VECTORS["channel.sk"]);
    expect(controlGroupKey(A, B, 0).pk).toBe(VECTORS["control.pk"]);
    expect(bytesToHex(controlGroupKey(A, B, 0).convKey)).toBe(
      VECTORS["control.convKey"],
    );
    expect(controlSignerGroupKey(A, B, 0).pk).toBe(VECTORS["controlSigner.pk"]);
    expect(guestbookGroupKey(A, B, 0).pk).toBe(VECTORS["guestbook.pk"]);
    expect(dissolvedGroupKey(A).pk).toBe(VECTORS["dissolved.pk"]);
    expect(channelRekeyGroupKey(A, B, 1).pk).toBe(VECTORS["channelRekey.pk"]);
    expect(baseRekeyGroupKey(A, B, 1).pk).toBe(VECTORS["baseRekey.pk"]);
    expect(bytesToHex(grantLocator(A, B))).toBe(VECTORS.grantLocator);
    expect(bytesToHex(pinsLocator(A, B))).toBe(VECTORS.pinsLocator);
    expect(bytesToHex(banlistLocator(A))).toBe(VECTORS.banlistLocator);
    expect(bytesToHex(inviteLinksLocator(A, B))).toBe(
      VECTORS.inviteLinksLocator,
    );
    expect(bytesToHex(recipientLocator(A, B, C, 3))).toBe(
      VECTORS.recipientLocator,
    );
    expect(bytesToHex(inviteBundleKey(new Uint8Array(16).fill(7)))).toBe(
      VECTORS.inviteBundleKey,
    );
    expect(bytesToHex(communityIdOf(A, B))).toBe(VECTORS.communityIdOf);
    expect(bytesToHex(epochKeyCommitment(2, R))).toBe(
      VECTORS.epochKeyCommitment,
    );
  });

  it("matches an independent construction of the A.1 layout", () => {
    // Rebuild `info = utf8(label) || 0x00 || id[32] || epoch_be[8]?` from
    // scratch, so the vectors above are anchored to the spec text and not just
    // to another implementation that could share a mistake.
    const info = (label: string, id: Uint8Array, epoch?: bigint) => {
      const l = new TextEncoder().encode(label);
      const out = new Uint8Array(
        l.length + 1 + 32 + (epoch !== undefined ? 8 : 0),
      );
      out.set(l, 0);
      out.set(id, l.length + 1);
      if (epoch !== undefined) {
        new DataView(out.buffer).setBigUint64(l.length + 33, epoch, false);
      }
      return out;
    };
    const derive = (
      label: string,
      ikm: Uint8Array,
      id: Uint8Array,
      e?: bigint,
    ) => hkdf(sha256, ikm, new Uint8Array(0), info(label, id, e), 32);

    // Stream addresses: the seed is a valid scalar with overwhelming
    // probability, so sk == seed and no retry counter is involved.
    expect(channelGroupKey(A, B, 0).pk).toBe(
      bytesToHex(schnorr.getPublicKey(derive("concord/channel", A, B, 0n))),
    );
    expect(controlGroupKey(A, B, 0).pk).toBe(
      bytesToHex(schnorr.getPublicKey(derive("concord/control", A, B, 0n))),
    );
    expect(controlSignerGroupKey(A, B, 0).pk).toBe(
      bytesToHex(
        schnorr.getPublicKey(derive("concord/control-signer", A, B, 0n)),
      ),
    );
    expect(guestbookGroupKey(A, B, 0).pk).toBe(
      bytesToHex(schnorr.getPublicKey(derive("concord/guestbook", A, B, 0n))),
    );

    // Locators are the raw hkdf output, epoch omitted entirely.
    expect(bytesToHex(grantLocator(A, B))).toBe(
      bytesToHex(derive("concord/grant", A, B)),
    );
    expect(bytesToHex(banlistLocator(A))).toBe(
      bytesToHex(derive("concord/banlist", A, new Uint8Array(32))),
    );
  });

  it("omits the epoch field entirely rather than encoding zero", () => {
    // The distinction the A.1 note exists for: an omitted epoch is 8 fewer
    // bytes of `info`, not eight zero bytes. Confusing the two yields a
    // self-consistent client that no one else can talk to.
    const withZeroEpoch = hkdf(
      sha256,
      A,
      new Uint8Array(0),
      (() => {
        const l = new TextEncoder().encode("concord/banlist");
        const out = new Uint8Array(l.length + 1 + 32 + 8);
        out.set(l, 0);
        return out;
      })(),
      32,
    );
    expect(bytesToHex(banlistLocator(A))).not.toBe(bytesToHex(withZeroEpoch));
  });
});

describe("group_key derivations", () => {
  it("derives deterministic, distinct addresses per label", () => {
    const chan = channelGroupKey(A, B, 0);
    const ctrl = controlGroupKey(A, B, 0);
    const gb = guestbookGroupKey(A, B, 0);
    expect(channelGroupKey(A, B, 0).pk).toBe(chan.pk);
    expect(new Set([chan.pk, ctrl.pk, gb.pk]).size).toBe(3);
  });

  it("keeps the split control plane's two derivations apart", () => {
    // Same community, same epoch, same-shaped inputs: the read key and the
    // signer address must never collide, or a legacy epoch and a split one
    // would land on the same address (CORD-02 §5).
    expect(controlGroupKey(A, B, 0).pk).not.toBe(
      controlSignerGroupKey(A, B, 0).pk,
    );
  });

  it("rotates the address with the epoch (unlinkable planes)", () => {
    expect(channelGroupKey(A, B, 0).pk).not.toBe(channelGroupKey(A, B, 1).pk);
    expect(controlGroupKey(A, B, 0).pk).not.toBe(controlGroupKey(A, B, 1).pk);
  });

  it("separates by id: two channels under one secret never share an address", () => {
    expect(channelGroupKey(A, B, 0).pk).not.toBe(channelGroupKey(A, C, 0).pk);
  });

  it("the dissolved address is epoch-free and key-free (community_id alone)", () => {
    expect(dissolvedGroupKey(A).pk).toBe(dissolvedGroupKey(A).pk);
    expect(dissolvedGroupKey(B).pk).not.toBe(dissolvedGroupKey(A).pk);
  });

  it("rekey addresses derive from the PRIOR secret at the NEW epoch", () => {
    const r1 = channelRekeyGroupKey(A, B, 1);
    expect(r1.pk).not.toBe(baseRekeyGroupKey(A, B, 1).pk);
    expect(channelRekeyGroupKey(A, B, 2).pk).not.toBe(r1.pk);
  });

  it("rejects inputs that are not 32 bytes", () => {
    expect(() => channelGroupKey(new Uint8Array(31), B, 0)).toThrow();
    expect(() => channelGroupKey(A, new Uint8Array(33), 0)).toThrow();
  });
});

describe("coordinates", () => {
  it("locators are 32 bytes, distinct, deterministic", () => {
    const g = grantLocator(A, B);
    expect(g.length).toBe(32);
    expect(bytesToHex(grantLocator(A, B))).toBe(bytesToHex(g));
    expect(bytesToHex(grantLocator(A, C))).not.toBe(bytesToHex(g));
    expect(bytesToHex(banlistLocator(A))).not.toBe(bytesToHex(g));
    expect(bytesToHex(inviteLinksLocator(A, B))).not.toBe(bytesToHex(g));
    expect(bytesToHex(pinsLocator(A, B))).not.toBe(bytesToHex(g));
  });

  it("recipient locators bind rotator, recipient, scope, and epoch", () => {
    const base = bytesToHex(recipientLocator(A, B, C, 1));
    expect(bytesToHex(recipientLocator(A, B, C, 1))).toBe(base);
    expect(bytesToHex(recipientLocator(B, A, C, 1))).not.toBe(base); // direction matters
    expect(bytesToHex(recipientLocator(A, B, C, 2))).not.toBe(base);
    expect(bytesToHex(recipientLocator(A, B, A, 1))).not.toBe(base);
  });

  it("invite bundle key derives from the token alone", () => {
    const token = new Uint8Array(16).fill(7);
    expect(bytesToHex(inviteBundleKey(token))).toBe(
      bytesToHex(inviteBundleKey(token)),
    );
    expect(bytesToHex(inviteBundleKey(new Uint8Array(16).fill(8)))).not.toBe(
      bytesToHex(inviteBundleKey(token)),
    );
  });
});

describe("community_id (A.4)", () => {
  it("commits to the owner and salt", () => {
    const id = communityIdOf(A, B);
    expect(id.length).toBe(32);
    expect(
      verifyCommunityId(bytesToHex(id), bytesToHex(A), bytesToHex(B)),
    ).toBe(true);
    expect(
      verifyCommunityId(bytesToHex(id), bytesToHex(C), bytesToHex(B)),
    ).toBe(false);
    expect(
      verifyCommunityId(bytesToHex(id), bytesToHex(A), bytesToHex(C)),
    ).toBe(false);
  });

  it("refuses malformed input rather than throwing", () => {
    expect(verifyCommunityId("nope", bytesToHex(A), bytesToHex(B))).toBe(false);
  });
});

describe("epoch-key commitment (A.5)", () => {
  it("is deterministic and binds epoch + key", () => {
    const c = epochKeyCommitment(2n, A);
    expect(bytesToHex(epochKeyCommitment(2n, A))).toBe(bytesToHex(c));
    expect(bytesToHex(epochKeyCommitment(3n, A))).not.toBe(bytesToHex(c));
    expect(bytesToHex(epochKeyCommitment(2n, B))).not.toBe(bytesToHex(c));
  });

  it("agrees whether the epoch arrives as number or bigint", () => {
    expect(bytesToHex(epochKeyCommitment(2, A))).toBe(
      bytesToHex(epochKeyCommitment(2n, A)),
    );
  });
});

describe("hex32", () => {
  it("round-trips and rejects malformed", () => {
    expect(bytesToHex(hex32(bytesToHex(A)))).toBe(bytesToHex(A));
    expect(() => hex32("abc")).toThrow();
    expect(() => hex32("zz".repeat(32))).toThrow();
  });
});

describe("derivation memo", () => {
  it("returns the same object for the same coordinates", () => {
    expect(channelGroupKey(A, B, 0)).toBe(channelGroupKey(A, B, 0));
  });

  it("computes convKey lazily, and only once", () => {
    let dirty = 0;
    onGroupKeyMemoDirty(() => dirty++);
    const key = channelGroupKey(A, B, 0);
    expect(dirty).toBe(1); // the derivation itself
    expect(exportGroupKeyMemo(100)[0].ck).toBeUndefined();

    const first = bytesToHex(key.convKey);
    expect(dirty).toBe(2); // convKey now known and worth persisting
    expect(bytesToHex(key.convKey)).toBe(first);
    expect(dirty).toBe(2); // second read is free
    expect(exportGroupKeyMemo(100)[0].ck).toBe(first);
  });

  it("hydrates from a persisted entry without re-deriving", () => {
    const before = channelGroupKey(A, B, 0);
    const persisted = exportGroupKeyMemo(100);
    expect(persisted).toHaveLength(1);
    // The persisted row must not spell the secret the derivation started from.
    expect(persisted[0].h).not.toContain(bytesToHex(A));

    _resetGroupKeyMemoForTests();
    importGroupKeyMemo(persisted);
    expect(channelGroupKey(A, B, 0).pk).toBe(before.pk);
    expect(bytesToHex(channelGroupKey(A, B, 0).sk)).toBe(bytesToHex(before.sk));
  });

  it("skips malformed persisted rows instead of trusting them", () => {
    importGroupKeyMemo([
      null,
      "nope",
      { h: "short", sk: "x", pk: "y" },
      { h: "a".repeat(64), sk: "b".repeat(64), pk: "zz".repeat(32) },
    ]);
    // Nothing was staged, so a derivation still computes for itself.
    expect(channelGroupKey(A, B, 0).pk).toBe(VECTORS["channel.pk"]);
  });

  it("keeps unclaimed hydrated entries on export", () => {
    // A community not opened this session must not lose its cache to the next
    // write.
    const seeded = [
      { h: "a".repeat(64), sk: "b".repeat(64), pk: "c".repeat(64) },
    ];
    importGroupKeyMemo(seeded);
    channelGroupKey(A, B, 0);
    const out = exportGroupKeyMemo(100);
    expect(out.map((e) => e.h)).toContain("a".repeat(64));
    expect(out).toHaveLength(2);
  });
});
